### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by caseymsmith** [TeamRocket-COSC425/MathCSClubWebsite#61]
needs own navigation within content that takes you to a certain part of the page, include a button to go back to top of page. (for concept: https://blackrockdigital.github.io/startbootstrap-scrolling-nav/) 

- [x] Section to see site members (who has signed up)
- [x] Admin capability to make other members admins
- [x] Admin capability to remove members
- [x] GC/MC teams & free agents (#84)

**Comment by tterrag1098** [comment]
Closed by #103
